website/website/urls.py
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
# from oscar.app import application
from app import application


urlpatterns = patterns(

    url(r'^i18n/', include('django.conf.urls.i18n')),

    # The Django admin is not officially supported; expect breakage.
    # Nonetheless, it's often useful for debugging.
    url(r'^admin/', include(admin.site.urls)),

    #For future PayPal integration
    # (r'^checkout/paypal/', include('paypal.express.urls')),


    url(r'', include(application.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.DOCUMENT_URL, document_root=settings.DOCUMENT_ROOT)

website/website/apps/address/models.py
# from oscar.apps.address.models import *

from oscar.core.loading import is_model_registered
from .abstract_models import AbstractUserAddress, AbstractCountry

__all__ = []


if not is_model_registered('address', 'UserAddress'):
    class UserAddress(AbstractUserAddress):
        pass

    __all__.append('UserAddress')


if not is_model_registered('address', 'Country'):
    class Country(AbstractCountry):
        pass

    __all__.append('Country')

website/website/apps/basket/models.py
__author__ = 'joseph'
from oscar.apps.basket.models import *

website/website/apps/catalogue/models.py
__author__ = 'joseph'
from oscar.apps.catalogue.models import *

website/website/apps/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

website/website/apps/customer/models.py
from oscar.apps.customer.models import *  # noqa

website/website/apps/payment/models.py
from oscar.apps.payment.models import *  # noqa

website/website/apps/shipping/models.py
__author__ = 'joseph'
from oscar.apps.shipping.models import *

website/website/apps/user/models.py
__author__ = 'joseph'

# file: your-project/apps/user/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from oscar.apps.customer.abstract_models import AbstractUser
from oscar.core.loading import get_class, get_model


class User(AbstractUser):
    serial_number = models.IntegerField(_("Serial Number"), null=True, blank=True)


    # def get_full_name(self):
    #     full_name = '%s %s' % (self.last_name.upper(), self.first_name)
    #     return full_name.strip()

    # class Meta:
    #     db_table = 'auth_user'

    # facility = models.CharField(_("Facility"), max_length=20)

    # address = models.OneToOneField(
    #     UserAddress, related_name='address', verbose_name=_("Address"))

website/website/apps/address/forms.py
from django.conf import settings
from django import forms

from oscar.core.loading import get_model
from oscar.views.generic import PhoneNumberMixin

UserAddress = get_model('address', 'useraddress')


class AbstractAddressForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        Set fields in OSCAR_REQUIRED_ADDRESS_FIELDS as required.
        """
        super(AbstractAddressForm, self).__init__(*args, **kwargs)
        field_names = (set(self.fields) &
                       set(settings.OSCAR_REQUIRED_ADDRESS_FIELDS))
        for field_name in field_names:
            self.fields[field_name].required = True


class UserAddressForm(PhoneNumberMixin, AbstractAddressForm):

    class Meta:
        model = UserAddress
        fields = [
            'title', 'first_name', 'last_name',
            'line1', 'line2', 'line3', 'line4',
            'state', 'postcode', 'country',
            'phone_number', 'notes',
        ]

    def __init__(self, user, *args, **kwargs):
        super(UserAddressForm, self).__init__(*args, **kwargs)
        self.instance.user = user

website/website/apps/checkout/forms.py
from django import forms


class StripeTokenForm(forms.Form):
    stripeEmail = forms.EmailField(widget=forms.HiddenInput())
    stripeToken = forms.CharField(widget=forms.HiddenInput())



# from django import forms
#
# # from oscar.apps.payment import forms as payment_forms
# from ..payment import forms as payment_forms
# from oscar.apps.order.models import BillingAddress
#
#
# class BillingAddressForm(payment_forms.BillingAddressForm):
#     """
#     Extended version of the core billing address form that adds a field so
#     customers can choose to re-use their shipping address.
#     """
#     SAME_AS_SHIPPING, NEW_ADDRESS = 'same', 'new'
#     CHOICES = (
#         (SAME_AS_SHIPPING, 'Use shipping address'),
#         (NEW_ADDRESS, 'Enter a new address'),
#     )
#     same_as_shipping = forms.ChoiceField(
#         widget=forms.RadioSelect, choices=CHOICES, initial=SAME_AS_SHIPPING)
#
#     class Meta(payment_forms.BillingAddressForm):
#         model = BillingAddress
#         exclude = ('search_text', 'first_name', 'last_name')
#         # exclude = ('search_text', 'first_name', 'last_name')
#
#     def __init__(self, shipping_address, data=None, *args, **kwargs):
#         # Store a reference to the shipping address
#         self.shipping_address = shipping_address
#
#         super(BillingAddressForm, self).__init__(data, *args, **kwargs)
#
#         # If no shipping address (eg a download), then force the
#         # 'same_as_shipping' field to have a certain value.
#         if shipping_address is None:
#             self.fields['same_as_shipping'].choices = (
#                 (self.NEW_ADDRESS, 'Enter a new address'),)
#             self.fields['same_as_shipping'].initial = self.NEW_ADDRESS
#
#         # If using same address as shipping, we don't need require any of the
#         # required billing address fields.
#         if data and data.get('same_as_shipping', None) == self.SAME_AS_SHIPPING:
#             for field in self.fields:
#                 if field != 'same_as_shipping':
#                     self.fields[field].required = False
#
#     def _post_clean(self):
#         # Don't run model validation if using shipping address
#         if self.cleaned_data.get('same_as_shipping') == self.SAME_AS_SHIPPING:
#             return
#         super(BillingAddressForm, self)._post_clean()
#
#     def save(self, commit=True):
#         if self.cleaned_data.get('same_as_shipping') == self.SAME_AS_SHIPPING:
#             # Convert shipping address into billing address
#             billing_addr = BillingAddress()
#             self.shipping_address.populate_alternative_model(billing_addr)
#             if commit:
#                 billing_addr.save()
#             return billing_addr
#         return super(BillingAddressForm, self).save(commit)

website/website/apps/customer/forms.py
import string
import random

from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.models import get_current_site
from django.core.exceptions import ValidationError
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

from oscar.core.loading import get_profile_class, get_class, get_model
from oscar.core.compat import get_user_model, existing_user_fields
from oscar.apps.customer.utils import get_password_reset_url, normalise_email
from oscar.core.validators import password_validators
from oscar.apps.customer.forms import EmailUserCreationForm as CoreEmailUserCreationForm

Dispatcher = get_class('customer.utils', 'Dispatcher')
CommunicationEventType = get_model('customer', 'communicationeventtype')
ProductAlert = get_model('customer', 'ProductAlert')
UserAddressForm = get_class('address.forms', 'UserAddressForm')
User = get_user_model()


def generate_username():
    # Python 3 uses ascii_letters. If not available, fallback to letters
    try:
        letters = string.ascii_letters
    except AttributeError:
        letters = string.letters
    uname = ''.join([random.choice(letters + string.digits + '_')
                     for i in range(30)])
    try:
        User.objects.get(username=uname)
        return generate_username()
    except User.DoesNotExist:
        return uname


class PasswordResetForm(auth_forms.PasswordResetForm):
    """
    This form takes the same structure as its parent from django.contrib.auth
    """
    communication_type_code = "PASSWORD_RESET"

    def save(self, domain_override=None, use_https=False, request=None,
             **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        site = get_current_site(request)
        if domain_override is not None:
            site.domain = site.name = domain_override
        email = self.cleaned_data['email']
        active_users = User._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            reset_url = self.get_reset_url(site, request, user, use_https)
            ctx = {
                'user': user,
                'site': site,
                'reset_url': reset_url}
            messages = CommunicationEventType.objects.get_and_render(
                code=self.communication_type_code, context=ctx)
            Dispatcher().dispatch_user_messages(user, messages)

    def get_reset_url(self, site, request, user, use_https):
        # the request argument isn't used currently, but implementors might
        # need it to determine the correct subdomain
        reset_url = "%s://%s%s" % (
            'https' if use_https else 'http',
            site.domain,
            get_password_reset_url(user))

        return reset_url


class SetPasswordForm(auth_forms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        # Enforce password validations for the new password
        self.fields['new_password1'].validators += password_validators


class PasswordChangeForm(auth_forms.PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        # Enforce password validations for the new password
        self.fields['new_password1'].validators += password_validators


class EmailAuthenticationForm(AuthenticationForm):
    """
    Extends the standard django AuthenticationForm, to support 75 character
    usernames. 75 character usernames are needed to support the EmailOrUsername
    auth backend.
    """
    username = forms.EmailField(label=_('Email address'))
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    def __init__(self, host, *args, **kwargs):
        self.host = host
        super(EmailAuthenticationForm, self).__init__(*args, **kwargs)

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if url and is_safe_url(url, self.host):
            return url


class ConfirmPasswordForm(forms.Form):
    """
    Extends the standard django AuthenticationForm, to support 75 character
    usernames. 75 character usernames are needed to support the EmailOrUsername
    auth backend.
    """
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        super(ConfirmPasswordForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_password(self):
        password = self.cleaned_data['password']
        if not self.user.check_password(password):
            raise forms.ValidationError(
                _("The entered password is not valid!"))
        return password


# from ..address.forms import UserAddressForm, UserAddress
# # from ..address.models import UserAddress, Country
#
# class AddressCreationForm(UserAddressForm):
#     form_class = UserAddressForm
#
#     def __init__(self, host=None, *args, **kwargs):
#         self.host = host
#         super(AddressCreationForm, self).__init__(*args, **kwargs)
#
#     class Meta:
#         model = UserAddress
#         fields = [
#             'title', 'first_name', 'last_name',
#             'line1', 'line2', 'line3', 'line4',
#             'state', 'postcode', 'country',
#             'phone_number',
#         ]
#
#     # def clean_email(self):
#     #     """
#     #     Checks for existing users with the supplied email address.
#     #     """
#     #     email = normalise_email(self.cleaned_data['email'])
#     #     if User._default_manager.filter(email__iexact=email).exists():
#     #         raise forms.ValidationError(
#     #             _("A user with that email address already exists"))
#     #     return email
#     #
#     # def clean_password2(self):
#     #     password1 = self.cleaned_data.get('password1', '')
#     #     password2 = self.cleaned_data.get('password2', '')
#     #     if password1 != password2:
#     #         raise forms.ValidationError(
#     #             _("The two password fields didn't match."))
#     #     return password2
#     #
#     # def clean_redirect_url(self):
#     #     url = self.cleaned_data['redirect_url'].strip()
#     #     if url and is_safe_url(url, self.host):
#     #         return url
#     #     return settings.LOGIN_REDIRECT_URL
#
#     def save(self, commit=True):
#         # user = super(AddressCreationForm, self).save(commit=False)
#         # user.set_password(self.cleaned_data['password1'])
#         # UserAddressForm.__init__(user=user)
#         # self.instance.user = user
#         # if 'username' in [f.name for f in User._meta.fields]:
#         #     user.username = generate_username()
#         # if commit:
#         #     user.save()
#         #     print user.username
#         address = super(AddressCreationForm, self).save(commit=False)
#         if commit:
#             # user.save()
#             # print user.username
#             address.save()
#             print address
#         return address


# from ..address.models import UserAddress
# from django.forms.models import inlineformset_factory


def validate_serial(num):
    if num > 22200000:
        raise ValidationError('%s is not a valid serial number!' % num)


class EmailUserCreationForm(CoreEmailUserCreationForm):
    # form_class = User

    first_name = forms.CharField(label=_('First name'))
    last_name = forms.CharField(label=_('Last name'))
    # facility = forms.CharField(label=_('Facility'))
    serial_number = forms.IntegerField(error_messages={'required': 'Please enter a valid number.'},
                                label=_('Serial Number'), widget=forms.NumberInput,
                                help_text="From Control/Gating module", validators=[validate_serial])
    password1 = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput,
        validators=password_validators)
    password2 = forms.CharField(
        label=_('Confirm password'), widget=forms.PasswordInput)
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'serial_number')


    def __init__(self, host=None, *args, **kwargs):
        self.host = host
        super(EmailUserCreationForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """
        Checks for existing users with the supplied email address.
        """
        email = normalise_email(self.cleaned_data['email'])
        if User._default_manager.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                _("A user with that email address already exists"))
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data.get('password2', '')
        if password1 != password2:
            raise forms.ValidationError(
                _("The two password fields didn't match."))
        return password2

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if url and is_safe_url(url, self.host):
            return url
        return settings.LOGIN_REDIRECT_URL

    def save(self, commit=True):
        user = super(EmailUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if 'username' in [f.name for f in User._meta.fields]:
            user.username = generate_username()
        if commit:
            user.save()
        return user


class OrderSearchForm(forms.Form):
    date_from = forms.DateField(

website/website/apps/payment/forms.py
__author__ = 'joseph'

from oscar.apps.payment.forms import *
from oscar.apps.payment.forms import BankcardForm as BaseBankcardForm


# class BankcardForm(BaseBankcardForm):
#     # By default, this number field will accept any number. The only validation
#     # is whether it passes the luhn check. If you wish to only accept certain
#     # types of card, you can pass a types kwarg to BankcardNumberField, e.g.
#     #
#     # BankcardNumberField(types=[bankcards.VISA, bankcards.VISA_ELECTRON,])
#
#     number = BankcardNumberField()
#     ccv = BankcardCCVField()
#     start_month = BankcardStartingMonthField()
#     expiry_month = BankcardExpiryMonthField()
#
#     class Meta(BaseBankcardForm.Meta):
#         BaseBankcardForm.Meta.fields = ('number', 'ccv', 'expiry_month')
#         print ("Fields After Meta: ", BaseBankcardForm.Meta.fields)
#
#     def delete_non_child_fields(self):
#         """
#         Deletes any fields not needed for child products. Override this if
#         you want to e.g. keep the description field.
#         """
#         for field_name in ['start_month']:
#             if field_name in self.fields:
#                 del self.fields[field_name]

website/website/apps/quotation/forms.py
__author__ = 'joseph'

website/website/templates/customer/quotation/quotation_detail.html
{% extends "customer/baseaccountpage.html" %}
{% load currency_filters %}
{% load display_tags %}
{% load i18n %}
{% load reviews_tags %}

{% block extra_breadcrumbs %}
    <li>
        <a href="{% url 'customer:quotation-list' %}">{% trans 'Quotation history' %}</a>
    </li>
{% endblock %}

{% block tabcontent %}
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>{% trans 'Product' %}</th>
{#                <th>{% trans 'Dispatch date' %}</th>#}
                <th>{% trans 'Qty' %}</th>
                <th>{% trans 'Line price' %}</th>
{#                <th>{% trans 'Line price excl. tax' %}</th>#}
{#                <th>{% trans 'Line price incl. tax' %}</th>#}
            </tr>
        </thead>
        <tbody>
            {% for line in quotation.basket.lines.all %}
                {% with product=line.product %}
                    <tr>
                        <td>{{ line.description }}</td>
{#                        <td>{{ line.est_dispatch_date|default:"-" }}</td>#}
                        <td>{{ line.quantity }}</td>
                        <td>{{ line.price_excl_tax|currency:quotation.basket.currency }}</td>
{#                        <td>{{ line.line_price_before_discounts_excl_tax|currency:quotation.basket.currency }}</td>#}
{#                        <td>{{ line.line_price_before_discounts_incl_tax|currency:quotation.basket.currency }}</td>#}
{#                        <td width="90">#}
{#                            {% if product %}#}
{#                                <form id="line_form_{{ line.id }}" action="{% url 'customer:quotation-line' order_number=order.number line_id=line.id %}" method="POST">#}
{#                                    {% csrf_token %}#}
{#                                    <input type="hidden" name="action" value="reorder" />#}
{#                                    <button id="reorder_line_{{ line.id }}" class="btn btn-success" type="submit" data-loading-text="{% trans 'Re-ordering...' %}">{% trans 'Re-order' %}</button>#}
{#                                </form>#}
{#                            {% else %}#}
{#                                {% trans 'Not available anymore' %}#}
{#                            {% endif %}#}
{#                        </td>#}
                    </tr>
                {% endwith %}
            {% endfor %}

{#            {% with discounts=order.basket_discounts %}#}
{#                {% block discount_totals %}#}
{#                    {% if discounts %}#}
{#                        <tr>#}
{#                            <td colspan="2">{% trans "Basket total (excl. discounts)" %}</td>#}
{#                            <td colspan="2">{{ order.basket_total_before_discounts_incl_tax|currency:order.currency }}</td>#}
{#                        </tr>#}
{#                        {% for discount in discounts %}#}
{#                        <tr>#}
{#                            <td colspan="4">#}
{#                                <span class="label label-success">{% trans "Discount" %}</span>#}
{#                                {{ discount.offer_name }}#}
{#                            </td>#}
{#                            <td colspan="2">- {{ discount.amount|currency:order.currency }}</td>#}
{#                        </tr>#}
{#                        {% endfor %}#}
{#                    {% endif %}#}
{#                {% endblock discount_totals %}#}

{#                {% block basket_total %}#}
{#                    {% if discounts %}#}
{#                        <tr>#}
{#                            <th colspan="2">{% trans "Basket total (inc. discounts)" %}</th>#}
{#                            <td colspan="2">{{ quotation.total|currency:quotation.currency }}</td>#}
{#                        </tr>#}
{#                    {% else %}#}
{#                        <tr>#}
{#                            <th colspan="2">{% trans "Basket total" %}</th>#}
{#                            <td colspan="2">{{ quotation.total|currency:quotation.currency }}</td>#}
{#                        </tr>#}
{#                    {% endif %}#}
{#                {% endblock basket_total %}#}
{#            {% endwith %}#}

            {% block shipping_totals %}
                {% if order.has_shipping_discounts %}
                    <tr>
                        <td colspan="2">{% trans "Shipping total (excl. discounts)" %}</td>
                        <td colspan="2">{{ order.shipping_before_discounts_incl_tax|currency:order.currency }}</td>
                    </tr>
                    {% for discount in order.shipping_discounts %}
                    <tr>
                        <td colspan="4">
                            <span class="label label-success">{% trans "Discount" %}</span>
                            {{ discount.offer_name }}
                        </td>
                        <td colspan="2">- {{ discount.amount|currency:order.currency }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4">{% trans "Shipping total (inc. discounts)" %}</th>
                        <td colspan="2">{{ order.shipping_incl_tax|currency:order.currency }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <th colspan="2">{% trans "Shipping total" %}</th>
                        <td colspan="2">{{ quotation.shipping_incl_tax|currency:quotation.currency }}</td>
                    </tr>
                {% endif %}
            {% endblock %}

            {% block order_total %}
                <tr>
                    <th colspan="2">{% trans 'Quote total' %}</th>
                    <td colspan="2">{{ quotation.total|currency:quotation.currency }}</td>
                </tr>
            {% endblock order_total %}
        </tbody>
    </table>

    {% block quotation_actions %}
        <form id="order_form_{{ quotation.id }}" action="{% url 'customer:quotation' number=quotation.number %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="quotation_id" value="{{ quotation.id }}" />
            <input type="hidden" name="action" value="reorder" />
            <button type="submit" class="btn btn-success" data-loading-text="{% trans 'Proceeding to checkout...' %}">{% trans 'Order this quote' %}</button>
        </form>
    {% endblock quotation_actions %}

    <hr>

    <h2>{% trans 'Shipping Method' %}</h2>
    <p>{{ order.shipping_method }}</p>

    <hr>

    <h2>{% trans 'Shipping Address' %}</h2>

    <table class="table table-striped table-bordered">
        <tr>
            <th>{% trans 'Address' %}</th>
            <th>{% trans 'Contact Number' %}</th>
            <th>{% trans 'Shipping Notes' %}</th>
        </tr>
        <tr>
            <td>
                    {% for field in order.shipping_address.active_address_fields %}
                        {{ field }}<br/>
                    {% endfor %}
            </td>
            <td>{{ order.shipping_address.phone_number|default:"-" }}</td>
            <td>{{ order.shipping_address.notes|linebreaks }}</td>
        </tr>
    </table>
{% endblock tabcontent %}

website/website/templates/customer/quotation/quotation_list.html
{% extends "customer/baseaccountpage.html" %}
{% load i18n %}
{% load currency_filters %}
{% load staticfiles %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans 'Home' %}</a>
        </li>
        <li>
            <a href="{% url 'customer:summary' %}">{% trans 'Account' %}</a>
        </li>
        <li class="active">{% trans 'Quote request history' %}</li>
    </ul>
{% endblock %}

{% block tabcontent %}

{#    {% if quotations or form.is_bound %}#}
{#        <div class="well">#}
{#            <h2>{% trans "Filter" %}</h2>#}
{#            <form action="." method="get" class="form-horizontal">#}
{#                {% include "partials/form_fields.html" with form=form style='horizontal' %}#}
{#                <div class="form-group">#}
{#                    <div class="col-sm-offset-4 col-sm-8">#}
{#                        <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Filtering...' %}">{% trans 'Filter results' %}</button>#}
{#                        <a href="{% url 'customer:quotation-list' %}" class="btn btn-default">{% trans 'Reset' %}</a>#}
{#                    </div>#}
{#                </div>#}
{#            </form>#}
{#        </div>#}
{#    {% endif %}#}

    {% if quotations %}
        <h2>All quotes</h2>
        <table class="table table-striped table-bordered">
            <tr>
                <th>{% trans "Quote number" %}</th>
                <th>{% trans "Num items" %}</th>
                <th>{% trans "Total" %}</th>
                <th>{% trans "Date submitted" %}</th>
            </tr>
            {% for quotation in quotations %}
                <tr>
                    <td><a href="{% url 'customer:quotation' number=quotation.number%}">{{ quotation.number}}</a></td>
                    <td>{{ quotation.basket.num_items }}</td>
                    <td>{{ quotation.total|currency:quotation.currency }}</td>
                    <td>{{ quotation.date_placed }}</td>
                </tr>
            {% endfor %}
        </table>
        {% include "partials/pagination.html" %}
    {% else %}
        {% if form.is_bound %}
            <p>{% trans "No quote requests match your search." %}</p>
        {% else %}
            <p>{% trans "You haven't requsted any quotes." %}</p>
        {% endif %}
    {% endif %}

{% endblock tabcontent %}

{% block extrastyles %}
    {{ block.super }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.css">
{% endblock %}

{% block cdn_scripts %}
    {{ block.super }}
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block onbodyload %}
    {{ block.super }}
    $('#id_date_to, #id_date_from').datepicker({'dateFormat': 'yy-mm-dd'});
{% endblock %}